FROM fedora:36

RUN dnf install -y \
    'dnf-command(builddep)' \
    podman \
    git \
    ninja-build podman \
    libguestfs-tools \
    qemu-img \
    flex \
    bison \
    elfutils-libelf-devel \
    openssl-devel \
    glibc-static \
    automake \
    rsync \
    bc \
    hostname \
    libtool && \
    dnf builddep -y clang
RUN dnf install -y moby-engine
RUN mkdir -p /workdir
WORKDIR /workdir
ENV WORKDIR=/workdir
CMD ["sleep", "999d"]
