FROM fedora:36

RUN dnf install -y \
    'dnf-command(builddep)' \
    git \
    ninja-build \
    podman \
    libguestfs-tools \
    qemu-img \
    flex \
    bison \
    elfutils-libelf-devel \
    openssl-devel \
    glibc-static \
    automake \
    rsync \
    bc \
    hostname \
    libevent-devel \
    pcre-devel \
    libtool \
    sudo && \
    dnf builddep -y clang
RUN mkdir -p /workdir
WORKDIR /workdir
ENV WORKDIR=/workdir
CMD ["sleep", "999d"]
